---
title: "Registros de orquídeas (familia Orchidaceae) de Costa Rica"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
---

```{r carga-paquetes, message=FALSE, warning=FALSE, include=FALSE}
# Carga de paquetes
library(dplyr)
library(DT)
library(leaflet)
library(leaflet.extras)
library(leafem)
library(raster)
library(sf)
library(spData)
library(flexdashboard)
library(plotly)
library(tidyr)
```

```{r carga-capas}
# Carga de capas de orquídeas
orquideas <-
  sf::st_read(
  "https://raw.githubusercontent.com/gf0604-procesamientodatosgeograficos/2021i-datos/main/gbif/orchidaceae-cr-registros.csv",
  options = c(
    "X_POSSIBLE_NAMES=decimalLongitude",
    "Y_POSSIBLE_NAMES=decimalLatitude"
  ),
  quiet = TRUE
)

# Asignación de proyecciones
sf::st_crs(orquideas) = 4326

# Carga de la capa de provincias
provincias <-
   sf::st_read(
    "https://raw.githubusercontent.com/gf0604-procesamientodatosgeograficos/2021i-datos/main/ign/delimitacion-territorial-administrativa/cr_provincias_simp_wgs84.geojson",
    quiet = TRUE
  )

# Carga de la capa de cantones
cantones <-
   sf::st_read(
    "https://raw.githubusercontent.com/gf0604-procesamientodatosgeograficos/2021i-datos/main/ign/delimitacion-territorial-administrativa/cr_cantones_simp_wgs84.geojson",
    quiet = TRUE
  )

# Cruce espacial con la tabla de cantones y provincias
orquideas <- 
  orquideas %>%
  sf::st_join(cantones["canton"]) %>%
  sf::st_join(provincias["provincia"])

# Conversión de los valores
orquideas <- 
  orquideas %>%
  mutate(coordinateUncertaintyInMeters = as.numeric(coordinateUncertaintyInMeters)) %>%
  mutate(eventDate = as.Date(eventDate, "%Y-%m-%d"))

# Limpieza de los valores de alta incertidumbre
orquideas <-
  orquideas %>%
  filter(!is.na(coordinateUncertaintyInMeters) & coordinateUncertaintyInMeters <= 1000)


```

Registros de presencia
=======================================================================

Column {data-width=60}
-----------------------------------------------------------------------

### Cantidad de registros {.value-box}
```{r value-Box1, message=FALSE, warning=FALSE}
valueBox(value = nrow(orquideas), 
         color = "#fd8d3c"
)

```

### Cantidad de generos {.value-box}
```{r value-Box2, message=FALSE, warning=FALSE}
generos <-
  orquideas %>%
  filter(!is.na(genus) & genus != "") %>%
  group_by(genus) %>%
  summarise(registros=n_distinct(genus, na.rm=TRUE))

valueBox(value = nrow(generos), 
         color = "#f03b20"
)

```

### Cantidad de especies {.value-box}
```{r value-Box3, message=FALSE, warning=FALSE}
especies <-
  orquideas %>%
  filter(!is.na(species) & species != "") %>%
  group_by(species) %>%
  summarise(registros=n_distinct(species, na.rm=TRUE))

valueBox(value = nrow(especies), 
         color = "#bd0026"
)

```

row {data-height=400}
-----------------------------------------------------------------------

### Tabla de registros de presencia
```{r}
# Tabla de registros de presencia
orquideas %>%
  st_drop_geometry() %>%
  dplyr::select(species, stateProvince, canton, eventDate) %>%
  datatable(
    colnames = c("Especie", "Provincia", "Canton", "Fecha"),
    options = list(
      searchHighlight = TRUE,
      language = list(url = '//cdn.datatables.net/plug-ins/1.10.11/i18n/Spanish.json')
    )
  )
```

### Gráfico pastel: cantidad de registros de presencia por especies
```{r gráfico-pastel, message=FALSE, warning=FALSE}
orquis <-
  orquideas %>%
  st_drop_geometry() %>%
  filter(!is.na(species) & species != "") %>%
  group_by(especies =species) %>% 
  summarise(registros=n()) %>%
  arrange(desc(registros)) %>%
  slice(1:10)

orquis2 <-
  orquideas %>%
  st_drop_geometry() %>%
  filter(!is.na(species) & species != "") %>%
  group_by(especies =species) %>% 
  summarise(registros=n()) %>%
  arrange(desc(registros)) %>%
  slice(11:232) %>%
  group_by(especies=as.character("Otras")) %>%
  summarise(registros=sum(registros))

orquis3 <-
  merge(orquis, orquis2, all = TRUE)

# Gráfico tipo pastel
plot_ly(orquis3, labels =  ~especies, values= ~registros, type = 'pie',
                   textposition = 'inside',
                   insidetextfont = list(color = '#FFFFFF'),
                   textinfo = 'label+percent',
                   hoverinfo = "value",
                   showlegend = TRUE,
                   marker = list(line = list(color = "#ffffff", width = 1))
                   ) %>%
  layout(title = 'Registro de especies de orquídeas en Costa Rica') %>%
  config(locale = "es")
```

row {data-height=10}
-----------------------------------------------------------------------
**Elaborado por:** Christian Cabrera Umaña C01425, Katherine Trejos Porras C07869, Tatiana Ramírez Villalobos C06397

Mapa clustered de registros de presencia
=======================================================================
```{r mapa-1, message=FALSE, warning=FALSE}
# Creación de conjunto de datos
provincias_orquideas <-
  provincias %>%
  st_join(orquideas) %>%
  group_by(provincia.x) %>%
  summarize(especies = n_distinct(species, na.rm=TRUE))
  
# Paleta de colores
colores_especies <-
  colorNumeric(palette = "YlOrRd",
              domain = provincias_orquideas$especies,
               na.color = "transparent")

# Mapa Leaflet
leaflet() %>%
  setView(lng = -84.0, lat = 10.0, zoom = 8) %>%
  addProviderTiles(providers$OpenStreetMap.Mapnik, group = "OpenStreetMap") %>%
  addProviderTiles(providers$Esri.WorldImagery, group = "Imágenes de ESRI") %>%
  addPolygons(
    data = provincias_orquideas,
    fillColor = ~ colores_especies(provincias_orquideas$especies),
    fillOpacity = 0.7,
    stroke = TRUE,
    color = "black",
    weight = 1,
    group = "Registros por provincias" 
  ) %>%
  addCircleMarkers(
    data = orquideas,
    stroke = F,
    radius = 4,
    fillColor = '#E99D37',
    fillOpacity = 1,
    popup = paste(
      paste(
         "<strong>Especie:</strong>",
          orquideas$species
      ),
      paste(
        "<strong>Provincia:</strong>",
        orquideas$provincia
      ),
      paste(
        "<strong>Cantón:</strong>",
        orquideas$canton
      ),
      paste(
        "<strong>Fecha:</strong>",
        orquideas$eventDate
      ),
      sep = '<br/>'
    ),
    clusterOptions = markerClusterOptions(),
    group = "Registros de orquideas"
  ) %>%  
  addLayersControl(baseGroups = c("OpenStreetMap", "Imágenes de ESRI"),
                   overlayGroups = c("Registros de orquideas", "Registros por provincias")) %>%
  addScaleBar(position = "bottomleft", options = scaleBarOptions(imperial = FALSE)) %>%
  addSearchOSM() %>%
  addResetMapButton() %>%
  addMiniMap(position = "bottomleft") %>%
  addLegend(
    position = "bottomleft",
    pal = colores_especies,
    values = provincias_orquideas$especies,
    group = "Registros por provincias",
    title = "Cantidad de especies"
  )
  
```

Mapa raster de cantidad de especies
=======================================================================
```{r mapa-2, message=FALSE, warning=FALSE}
# Obtención de la capa de altitud
alt <-
  raster::getData(
    "worldclim",
    var = "alt",
    res = 0.5,
    lon = -84,
    lat = 10
  )

# Recorte de la capa de altitud
altitud <-
  alt %>%
  crop(provincias) %>%
  mask(provincias)

# Plantilla raster
plantilla_rast <-
  altitud %>%
  aggregate(fact = 10)

# Rasterización
registro_orqui_rast <-
  rasterize(orquideas,
            plantilla_rast,
            field = 1,
            fun = "count")

# Mapa raster

# Especies por provincias
orquideas_species <-
  provincias  %>%
  st_join(orquideas)  %>%
  group_by(provincia.x)  %>%
  summarize(especies = n_distinct(species, na.rm = TRUE))

# Paleta de colores de leaf
colores_especies <-
  colorNumeric(palette = "YlOrRd",
              domain = orquideas_species$especies,
               na.color = "transparent")

# Paleta de colores
pal <- colorNumeric(
  c("#fde0dd", "#fa9fb5", "#c51b8a"), 
  values(registro_orqui_rast), 
  na.color = "transparent"
)

# Mapa Leaflet
leaflet() %>%
  setView(lng = -84.0, lat = 10.0, zoom = 8) %>%
  addProviderTiles(providers$OpenStreetMap.Mapnik, group = "OpenStreetMap") %>%
  addProviderTiles(providers$Esri.WorldImagery, group = "Imágenes de ESRI") %>%
  addRasterImage(
    registro_orqui_rast,
    colors = pal,
    opacity = 0.8,
    group = "Registros de orquideas"
  ) %>%
  addPolygons(
    data = orquideas_species,
    fillColor = ~ colores_especies(orquideas_species$especies),
    fillOpacity = 0.7,
    stroke = TRUE,
    color = "black",
    weight = 1,
    group = "Registros por provincias" 
  ) %>%
  addLayersControl(baseGroups = c("OpenStreetMap", "Imágenes de ESRI"),
                   overlayGroups = c("Registros de orquideas", "Registros por provincias")) %>%
  addScaleBar(position = "bottomleft", options = scaleBarOptions(imperial = FALSE)) %>%
  addSearchOSM() %>%
  addResetMapButton() %>%
  addMiniMap(position = "bottomleft") %>%
  addLegend(
    position = "bottomleft",
    pal = colores_especies,
    values = orquideas_species$especies,
    group = "Registros por provincias",
    title = "Cantidad de especies"
  )%>%
addLegend(
    position = "bottomright",
    pal = pal,
    values = values(registro_orqui_rast),
    group = "Registros de orquideas",
    title = "Cantidad de <br> registros por celda"
)
```

